[versions]
minSdk = "21"
compileSdk = "33"
targetSdk = "33"

kotlin = "1.8.0"
kotlinxserialization = "1.4.1"
ktor = "2.2.1"
multiplatformsettings = "1.0.0-RC"

[libraries]
adapterdelegates4-kotlin-dsl = { module = "com.hannesdorfmann:adapterdelegates4-kotlin-dsl", version = "4.3.2" }
androidx-annotation = { module = "androidx.annotation:annotation", version = "1.5.0" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version = "1.5.1" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version = "2.1.4" }
crashkios = { module = "co.touchlab:crashkios", version = "0.6.0" }
desugar_jdk_libs = { module = "com.android.tools:desugar_jdk_libs", version = "1.2.2" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-test-annotations-common = { module = "org.jetbrains.kotlin:kotlin-test-annotations-common", version.ref = "kotlin" }
kotlin-test-common = { module = "org.jetbrains.kotlin:kotlin-test-common", version.ref = "kotlin" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version = "0.4.0" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxserialization" }
ktor-client-core-jvm = { module = "io.ktor:ktor-client-core-jvm", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
lottie = { module = "com.airbnb.android:lottie", version = "5.2.0" }
material = { module = "com.google.android.material:material", version = "1.7.0" }
multiplatform-settings = { module = "com.russhwolf:multiplatform-settings", version.ref = "multiplatformsettings" }
multiplatform-settings-test = { module = "com.russhwolf:multiplatform-settings-test", version.ref = "multiplatformsettings" }
okio = { module = "com.squareup.okio:okio", version = "3.2.0" }
picnic = { module = "com.jakewharton.picnic:picnic", version = "0.6.0" }
plugin-androidgradleplugin = { module = "com.android.tools.build:gradle", version = "7.3.1" }
plugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
plugin-kotlin-serialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
rxandroid = { module = "io.reactivex.rxjava2:rxandroid", version = "2.1.1" }
rxjava = { module = "io.reactivex.rxjava2:rxjava", version = "2.2.21" }
timber = { module = "com.jakewharton.timber:timber", version = "5.0.1" }
uuid = { module = "com.benasher44:uuid", version = "0.6.0" }
